apiVersion: ark.mckinsey.com/v1alpha1
kind: Agent
metadata:
  name: web-scraper
  labels:
    app: ark-playwright-mcp
    use-case: web-scraping
spec:
  description: Web scraping and browser automation agent powered by Playwright

  modelRef:
    name: default

  prompt: |
    You are a web scraping and browser automation specialist.

    When given a task:
    1. Use playwright-browser-browser-navigate to load the target page
    2. Use playwright-browser-browser-snapshot to understand page structure (preferred over vision)
    3. Use playwright-browser-browser-click, playwright-browser-browser-type, playwright-browser-browser-fill-form for interactions
    4. Use playwright-browser-browser-take-screenshot to capture visual content
    5. Use playwright-browser-browser-evaluate for complex JavaScript operations
    6. Use playwright-browser-browser-console-messages to debug issues

    Best Practices:
    - Always use playwright-browser-browser-snapshot first to get element references
    - Wait for page loads using navigation timeouts
    - Handle errors gracefully
    - Capture screenshots for verification
    - Use accessibility tree (snapshot) instead of vision when possible

  tools:
  # Navigation tools
  - name: playwright-browser-browser-navigate
    type: mcp
  - name: playwright-browser-browser-navigate-back
    type: mcp
  - name: playwright-browser-browser-tabs
    type: mcp
  - name: playwright-browser-browser-close
    type: mcp
  - name: playwright-browser-browser-resize
    type: mcp

  # Interaction tools
  - name: playwright-browser-browser-click
    type: mcp
  - name: playwright-browser-browser-type
    type: mcp
  - name: playwright-browser-browser-fill-form
    type: mcp
  - name: playwright-browser-browser-select-option
    type: mcp
  - name: playwright-browser-browser-drag
    type: mcp
  - name: playwright-browser-browser-hover
    type: mcp
  - name: playwright-browser-browser-press-key
    type: mcp
  - name: playwright-browser-browser-file-upload
    type: mcp
  - name: playwright-browser-browser-wait-for
    type: mcp

  # Inspection tools
  - name: playwright-browser-browser-snapshot
    type: mcp
  - name: playwright-browser-browser-take-screenshot
    type: mcp
  - name: playwright-browser-browser-console-messages
    type: mcp
  - name: playwright-browser-browser-network-requests
    type: mcp

  # Advanced tools
  - name: playwright-browser-browser-evaluate
    type: mcp
  - name: playwright-browser-browser-run-code
    type: mcp
  - name: playwright-browser-browser-handle-dialog
    type: mcp
  - name: playwright-browser-browser-pdf-save
    type: mcp

  # Optional: Mouse control tools (for vision mode)
  # - name: playwright-browser-browser-mouse-click-xy
  #   type: mcp
  # - name: playwright-browser-browser-mouse-move-xy
  #   type: mcp
  # - name: playwright-browser-browser-mouse-drag-xy
  #   type: mcp
