apiVersion: ark.mckinsey.com/v1alpha1
kind: Query
metadata:
  name: test-google
  labels:
    app: ark-playwright-mcp
    test: google
spec:
  input: |
    Please perform the following tasks:

    1. Navigate to https://google.com
    2. Wait for the page to load completely
    3. Get the page title from the accessibility snapshot
    4. Check the console logs for any errors

    Provide a summary of what you found, including the page title and
    whether there were any console errors.

  target:
    name: web-scraper
    type: agent

  timeout: 2m0s
  ttl: 1h0m0s
  type: user
